### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by lukakostic** [nothke/PicoSpaceProgram#1]
1. Fuel doesnt matter, you can just add thrusters without tanks
2. You can just hold left or right and spin up to infinite angular velocity without even taking off
2b. No damage from angular velocity (parts dont explode even when the ship is spinning 100 revolutions a second and the parts are slamming to the ground)
3. You can place parts disconnected from other parts
4. You can stack many parts in one position (overlap parts)
5. You need 4-5 thrusters to lift off with just the cockpit (are the tanks actually adding thruster strenght?)
6. Needs map view

**Comment by nothke** [comment]
1. Didn't have time to finish implementing, 90% of fuel code is there tho :D 
2. Yeah, I don't calculate every part's velocity for crashing, but only whole craft, that is why spinning does nothing
3. Tho unrealistic, it gives some more artistic freedom :D 
4. ^
5. Every part adds mass, but it's possible that I've done something wrong there when applying force, I'll need to check.
6. Yes! But I'll need to rewrite the majority of draw code for that :'(

**Comment by lukakostic** [comment]
with the 5. If you place like 4 thrusters (no tanks or anything else) it will barely or wont even lift up. But if i put like 2 tanks and 2 thrusters below it flies just fine. So more mass = easier liftoff ?? idk seems weird
